"""Turn-grounding: pivotal user-correction extraction feeds the distill prompt."""

from clawjournal.skill.select import SkillCandidate, SkillCorpus
from clawjournal.skill.turns import (
    TurnExcerpt,
    enrich_corpus_with_turns,
    extract_correction_turns,
    is_correction,
)


def _u(text):
    return {"role": "user", "content": text}


def _a(text, tools=()):
    msg = {"role": "assistant", "content": text}
    if tools:
        msg["tool_uses"] = [{"tool": t, "input": {}, "output": "", "status": "ok"}
                            for t in tools]
    return msg


def test_correction_signals():
    assert is_correction("No, that's not what I asked — fix it in the Dockerfile instead")
    assert is_correction("revert that last change")
    assert is_correction("wait, you missed the migration file")
    assert is_correction("it still fails on the same input")
    assert is_correction("plz fix it properly")           # prior fix was inadequate
    assert not is_correction("looks good, now add tests please")
    assert not is_correction("thanks! ship it")
    # "fix it and merge" is a go-ahead on a bug the AGENT found, not a redirect
    assert not is_correction("fix it and merge")
    # a long new-task spec that happens to contain a signal word deep inside
    assert not is_correction("please add a feature. " + "x " * 400 + "use tabs instead")


def test_injected_bodies_are_not_the_human():
    # expanded skill/slash-command content and compaction summaries arrive with
    # role=user and imperative phrasing ("...instead") but must never excerpt.
    skill_body = ("Run the workflow-backed code review at high effort instead of "
                  'reviewing inline.\n\nInvoke: Workflow({ name: "code-review" })\n\nEtc.')
    compaction = ("This session is being continued from a previous conversation that "
                  "ran out of context. The user said the fix was wrong and asked to revert.")
    msgs = [_u("review this PR"), _a("Reviewing inline now."),
            _u(skill_body), _u(compaction)]
    assert extract_correction_turns(msgs) == []


def test_extracts_before_correction_after():
    msgs = [
        _u("add retry logic to the uploader"),
        _a("Done — retries added and all tests pass."),
        _u("No, that's not the root cause; fix it in the connection pool instead"),
        _a("You're right — the pool was recycling live connections. Fixed there."),
    ]
    (ex,) = extract_correction_turns(msgs)
    assert "retries added" in ex.before
    assert "connection pool" in ex.correction
    assert "recycling live connections" in ex.after


def test_first_user_message_is_the_task_not_a_correction():
    # a task that LOOKS like a correction ("don't...") must not produce an excerpt
    msgs = [_u("don't use pandas for this, write plain csv"), _a("ok, plain csv it is")]
    assert extract_correction_turns(msgs) == []


def test_noise_user_messages_skipped_and_reminders_stripped():
    msgs = [
        _u("build the exporter"),
        _a("Exporter built."),
        _u("<command-name>/compact</command-name>"),          # harness wrapper, not the human
        _u("<system-reminder>ignore me</system-reminder>looks good, continue"),
        _u("Caveat: The messages below were generated by the user while running local commands."),
    ]
    assert extract_correction_turns(msgs) == []   # nothing here is a real correction


def test_caps_excerpts_and_falls_back_to_tool_names():
    msgs = [_u("task")]
    for i in range(4):
        msgs += [_a("", tools=("Edit", "Bash")),               # no prose -> tools fallback
                 _u(f"no, still broken, attempt {i}")]
    got = extract_correction_turns(msgs, max_excerpts=2)
    assert len(got) == 2
    assert got[0].before == "(tools: Edit, Bash)"


def test_correction_with_no_prior_agent_activity_is_dropped():
    msgs = [_u("task"), _u("no, wrong")]   # user twice in a row, agent never acted
    assert extract_correction_turns(msgs) == []


def test_enrich_populates_candidates_and_survives_bad_blobs():
    ok = SkillCandidate(session_id="s1", project="p", source="claude", kind="avoid")
    bad = SkillCandidate(session_id="s2", project="p", source="claude", kind="do")
    corpus = SkillCorpus(window_start="a", window_end="b",
                         failures=[ok], successes=[bad])

    def loader(conn, sid):
        if sid == "s2":
            raise OSError("blob unreadable")
        return {"messages": [
            _u("task"), _a("Shipped the workaround."),
            _u("no — fix it in the image build instead"), _a("Moved into the Dockerfile."),
        ]}

    enrich_corpus_with_turns(None, corpus, loader=loader)
    assert len(ok.pivotal_excerpts) == 1
    assert "image build" in ok.pivotal_excerpts[0].correction
    assert bad.pivotal_excerpts == []                 # bad blob degraded, not fatal


def test_excerpts_reach_prompt_scrubbed():
    from clawjournal.redaction.anonymizer import Anonymizer
    from clawjournal.skill.distill import _candidate_aliases, build_prompt

    c = SkillCandidate(session_id="s1", project="p", source="claude", kind="avoid")
    c.pivotal_excerpts = [TurnExcerpt(
        before="deployed with AWS_SECRET_ACCESS_KEY=AKIAIOSFODNN7EXAMPLEKEYXX set",
        correction="no — the token leaked, rotate it and read creds from the env instead",
        after="rotated and moved to env lookup",
    )]
    corpus = SkillCorpus(window_start="a", window_end="b", failures=[c])
    prompt = build_prompt(corpus, Anonymizer(), _candidate_aliases(corpus))
    assert "pivotal_turn_1" in prompt and "user_correction" in prompt
    assert "rotate it" in prompt                      # substance kept
    assert "AKIAIOSFODNN7EXAMPLEKEYXX" not in prompt  # secret scrubbed pre-egress
