"""Turn-grounding: pivotal user-correction extraction feeds the distill prompt."""

from clawjournal.skill.select import SkillCandidate, SkillCorpus
from clawjournal.skill.turns import (
    TurnExcerpt,
    excerpts_for_session,
    extract_correction_turns,
    is_correction,
)


def _u(text):
    return {"role": "user", "content": text}


def _a(text, tools=()):
    msg = {"role": "assistant", "content": text}
    if tools:
        msg["tool_uses"] = [{"tool": t, "input": {}, "output": "", "status": "ok"}
                            for t in tools]
    return msg


def test_correction_signals():
    assert is_correction("No, that's not what I asked — fix it in the Dockerfile instead")
    assert is_correction("revert that last change")
    assert is_correction("wait, you missed the migration file")
    assert is_correction("it still fails on the same input")
    assert is_correction("plz fix it properly")           # prior fix was inadequate
    assert not is_correction("looks good, now add tests please")
    assert not is_correction("thanks! ship it")
    # "fix it and merge" is a go-ahead on a bug the AGENT found, not a redirect
    assert not is_correction("fix it and merge")
    # a long new-task spec that happens to contain a signal word deep inside
    assert not is_correction("please add a feature. " + "x " * 400 + "use tabs instead")


def test_injected_bodies_are_not_the_human():
    # expanded skill/slash-command content and compaction summaries arrive with
    # role=user and imperative phrasing ("...instead") but must never excerpt.
    skill_body = ("Run the workflow-backed code review at high effort instead of "
                  'reviewing inline.\n\nInvoke: Workflow({ name: "code-review" })\n\nEtc.')
    compaction = ("This session is being continued from a previous conversation that "
                  "ran out of context. The user said the fix was wrong and asked to revert.")
    msgs = [_u("review this PR"), _a("Reviewing inline now."),
            _u(skill_body), _u(compaction)]
    assert extract_correction_turns(msgs) == []


def test_extracts_before_correction_after():
    msgs = [
        _u("add retry logic to the uploader"),
        _a("Done — retries added and all tests pass."),
        _u("No, that's not the root cause; fix it in the connection pool instead"),
        _a("You're right — the pool was recycling live connections. Fixed there."),
    ]
    (ex,) = extract_correction_turns(msgs)
    assert "retries added" in ex.before
    assert "connection pool" in ex.correction
    assert "recycling live connections" in ex.after


def test_first_user_message_is_the_task_not_a_correction():
    # a task that LOOKS like a correction ("don't...") must not produce an excerpt
    msgs = [_u("don't use pandas for this, write plain csv"), _a("ok, plain csv it is")]
    assert extract_correction_turns(msgs) == []


def test_noise_user_messages_skipped_and_reminders_stripped():
    msgs = [
        _u("build the exporter"),
        _a("Exporter built."),
        _u("<command-name>/compact</command-name>"),          # harness wrapper, not the human
        _u("<system-reminder>ignore me</system-reminder>looks good, continue"),
        _u("Caveat: The messages below were generated by the user while running local commands."),
    ]
    assert extract_correction_turns(msgs) == []   # nothing here is a real correction


def test_caps_excerpts_and_falls_back_to_tool_names():
    msgs = [_u("task")]
    for i in range(4):
        msgs += [_a("", tools=("Edit", "Bash")),               # no prose -> tools fallback
                 _u(f"no, still broken, attempt {i}")]
    got = extract_correction_turns(msgs, max_excerpts=2)
    assert len(got) == 2
    assert got[0].before == "(tools: Edit, Bash)"


def test_correction_with_no_prior_agent_activity_is_dropped():
    msgs = [_u("task"), _u("no, wrong")]   # user twice in a row, agent never acted
    assert extract_correction_turns(msgs) == []


def test_excerpts_for_session_extracts_and_survives_bad_blobs():
    def loader(conn, sid):
        if sid == "s2":
            raise OSError("blob unreadable")
        return {"messages": [
            _u("task"), _a("Shipped the workaround."),
            _u("no — fix it in the image build instead"), _a("Moved into the Dockerfile."),
        ]}

    got = excerpts_for_session(None, "s1", loader=loader)
    assert len(got) == 1 and "image build" in got[0].correction
    assert excerpts_for_session(None, "s2", loader=loader) == []   # degraded, not fatal


def test_excerpts_reach_prompt_scrubbed():
    from clawjournal.redaction.anonymizer import Anonymizer
    from clawjournal.skill.distill import _candidate_aliases, build_prompt

    c = SkillCandidate(session_id="s1", project="p", source="claude", kind="avoid")
    c.pivotal_excerpts = [TurnExcerpt(
        before="deployed with AWS_SECRET_ACCESS_KEY=AKIAIOSFODNN7EXAMPLEKEYXX set",
        correction="no — the token leaked, rotate it and read creds from the env instead",
        after="rotated and moved to env lookup",
    )]
    corpus = SkillCorpus(window_start="a", window_end="b", failures=[c])
    prompt = build_prompt(corpus, Anonymizer(), _candidate_aliases(corpus))
    assert "pivotal_turn_1" in prompt and "user_correction" in prompt
    assert "rotate it" in prompt                      # substance kept
    assert "AKIAIOSFODNN7EXAMPLEKEYXX" not in prompt  # secret scrubbed pre-egress


# --- environment feedback ----------------------------------------------------

def _tu(tool, arg, status="success", output=""):
    return {"tool": tool, "input": {"arg": arg}, "status": status,
            "output": {"text": output} if output else {}}


def _at(*tool_uses):
    return {"role": "assistant", "content": "", "tool_uses": list(tool_uses)}


def test_error_recovery_excerpt_extracted():
    from clawjournal.skill.turns import extract_error_recoveries
    msgs = [
        _u("fix the config"),
        _at(_tu("Edit", "old text", status="error",
                output="String to replace not found in file.")),
        _at(_tu("Edit", "corrected exact text", status="success")),
    ]
    (ex,) = extract_error_recoveries(msgs)
    assert ex.action.startswith("Edit: old text")
    assert "not found in file" in ex.error
    assert "corrected exact text" in ex.recovery


def test_benign_and_human_rejection_errors_skipped():
    from clawjournal.skill.turns import extract_error_recoveries
    msgs = [
        _at(_tu("Grep", "needle", status="error", output="No matches found")),
        _at(_tu("Grep", "needle2", status="success")),
        _at(_tu("Bash", "rm -rf /tmp/x", status="error",
                output="Permission to use Bash with command rm -rf has been denied.")),
        _at(_tu("Bash", "ls", status="success")),
    ]
    assert extract_error_recoveries(msgs) == []   # probing + human rejection: not env lessons


def test_error_signature_normalizes_and_rejects_generic():
    from clawjournal.skill.turns import error_signature
    a = error_signature({"text": "Error at /Users/kai/proj/file.py line 42: bad frobnicate"})
    b = error_signature({"text": "Error at /home/other/app/main.py line 7: bad frobnicate"})
    assert a == b                                  # paths + numbers collapsed -> same cluster
    assert error_signature({"text": "Exit code 1"}) == ""   # too generic to cluster
    assert error_signature({"text": "Exit code 1\npytest: 3 tests failed in module x"}) != ""


def test_excerpts_for_session_puts_corrections_first_and_caps():
    def loader(conn, sid):
        return {"messages": [
            _u("task"),
            _at(_tu("Bash", "pytest -q", status="error",
                    output="ImportError: cannot import name frobnicate")),
            _at(_tu("Bash", "pip install -e . && pytest -q", status="success")),
            _a("All green now."),
            _u("no, that's not what I asked — revert the dep change"),
            _a("Reverted."),
        ]}
    got = excerpts_for_session(None, "s1", loader=loader)
    assert hasattr(got[0], "correction")           # human feedback leads
    assert any(hasattr(t, "recovery") for t in got)  # env recovery rides along
    assert len(got) <= 3


def test_add_env_candidates_clusters_across_sessions():
    from clawjournal.skill.turns import add_env_candidates
    corpus = SkillCorpus(window_start="a", window_end="b",
                         eligible_session_ids=["s1", "s2", "s3"])

    def loader(conn, sid):
        return {"project": "p", "source": "claude", "start_time": "2026-07-01T00:00:00+00:00",
                "messages": [
                    _at(_tu("Write", f"/tmp/{sid}.py", status="error",
                            output="File has not been read yet. Read it first before writing to it.")),
                    _at(_tu("Write", f"/tmp/{sid}.py", status="success")),
                ]}

    add_env_candidates(None, corpus, loader=loader)
    (c,) = corpus.failures
    assert c.kind == "avoid" and c.support_count == 3      # REAL session count
    assert "3 distinct sessions" in c.learning_summary
    (ex,) = c.pivotal_excerpts
    assert "not been read yet" in ex.error and ex.recovery  # recovery example captured
    assert corpus.total_failures == 1


def test_add_env_candidates_requires_min_recurrence():
    from clawjournal.skill.turns import add_env_candidates
    corpus = SkillCorpus(window_start="a", window_end="b",
                         eligible_session_ids=["s1", "s2"])

    def loader(conn, sid):
        return {"messages": [_at(_tu("Edit", "x", status="error",
                                     output="String to replace not found in file."))]}

    add_env_candidates(None, corpus, loader=loader)        # only 2 sessions < min 3
    assert corpus.failures == []


def test_env_excerpts_render_scrubbed_in_prompt():
    from clawjournal.redaction.anonymizer import Anonymizer
    from clawjournal.skill.distill import _candidate_aliases, build_prompt
    from clawjournal.skill.turns import EnvExcerpt

    c = SkillCandidate(session_id="s1", project="p", source="claude", kind="avoid")
    c.pivotal_excerpts = [EnvExcerpt(
        action="Bash: export TOKEN=ghp_9f8AexampleSECRETtokenValue123456 && ./deploy",
        error="401 unauthorized from registry",
        recovery="Bash: read token from env file, then ./deploy",
    )]
    corpus = SkillCorpus(window_start="a", window_end="b", failures=[c])
    prompt = build_prompt(corpus, Anonymizer(), _candidate_aliases(corpus))
    assert "env_recovery_1" in prompt and "failed_action" in prompt
    assert "401 unauthorized" in prompt
    assert "ghp_9f8AexampleSECRETtokenValue123456" not in prompt   # secret scrubbed pre-egress


def test_error_signature_skips_traceback_preamble():
    from clawjournal.skill.turns import error_signature
    out = {"text": "Exit code 1\nTraceback (most recent call last):\n"
                   '  File "/app/x.py", line 3, in <module>\n'
                   "KeyError: 'partResults'"}
    assert error_signature(out) == "keyerror: 'partresults'"   # the informative line


# --- human-rejection channel + precision fixes -------------------------------

def test_questions_weighing_options_are_not_corrections():
    # interrogative "instead" = weighing an option, not redirecting the agent
    assert not is_correction("another question: can we just use gpt 5.5 as the judge "
                             "instead of both gpt 5.5 and opus 4.8?")
    assert not is_correction("can you use the default Claude headless md instead of API key?")
    assert not is_correction("what's the impact of using opus 4.8 high instead of xhigh?")
    # declarative "instead" is still a redirect
    assert is_correction("let's ground by all these extracted raw traces instead")
    assert is_correction("I don't want the swe-bench-style tasks, instead let's synthesize")


def test_teammate_relays_are_not_corrections():
    relay = ('Another Claude session sent a message: <teammate-message teammate_id="b">'
             "no, that's wrong — revert it</teammate-message>")
    msgs = [_u("task"), _a("Working on it."), _u(relay)]
    assert extract_correction_turns(msgs) == []


def test_add_rejection_candidate_clusters_across_sessions():
    from clawjournal.skill.turns import add_rejection_candidate
    corpus = SkillCorpus(window_start="a", window_end="b",
                         eligible_session_ids=["s1", "s2", "s3"])
    denials = {
        "s1": "The user doesn't want to take this action right now. STOP what you are doing.",
        "s2": ("Permission for this action was denied by the Claude Code auto mode "
               "classifier. Reason: [Git Destructive] Deleting remote branch `x`."),
        "s3": "Permission to use Bash with command git push origin main has been denied.",
    }

    def loader(conn, sid):
        return {"project": "p", "source": "claude",
                "start_time": "2026-07-01T00:00:00+00:00",
                "messages": [_at(_tu("Bash", "git push origin main", status="error",
                                     output=denials[sid]))]}

    add_rejection_candidate(None, corpus, loader=loader)
    (c,) = corpus.failures
    assert c.title == "User-Rejected Actions" and c.support_count == 3
    assert "3 distinct sessions" in c.learning_summary
    assert "Git Destructive" in c.learning_summary          # classifier class surfaced
    assert len(c.pivotal_excerpts) == 3
    assert c.pivotal_excerpts[0].before.startswith("attempted: Bash: git push")
    assert c.pivotal_excerpts[0].correction.startswith("rejected: ")


def test_add_rejection_candidate_requires_min_recurrence():
    from clawjournal.skill.turns import add_rejection_candidate
    corpus = SkillCorpus(window_start="a", window_end="b",
                         eligible_session_ids=["s1", "s2"])

    def loader(conn, sid):
        return {"messages": [_at(_tu("Bash", "rm -rf x", status="error",
                                     output="The user doesn't want to take this action right now."))]}

    add_rejection_candidate(None, corpus, loader=loader)   # 2 sessions < min 3
    assert corpus.failures == []
